import type { Metadata } from 'next';
import './globals.css';
import { Geist, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Providers } from './providers';

const geistHeading = Geist({ subsets: ['latin'], variable: '--font-heading' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn('h-full antialiased', 'font-sans', inter.variable, geistHeading.variable)}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
